"""rename address

Revision ID: 046490dd6d85
Revises: 0a64c3a9e964
Create Date: 2024-05-30 11:43:04.023667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046490dd6d85'
down_revision = '0a64c3a9e964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
