"""rename department

Revision ID: 0a64c3a9e964
Revises: 75bf45db4059
Create Date: 2024-05-30 11:35:22.248932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a64c3a9e964'
down_revision = '75bf45db4059'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###   